---
version: 2.1

orbs:
  go: circleci/go@1.7.1

resource_class: medium
executors:
  golang:
    docker:
      - image: cimg/go:1.18

jobs:
  build:
    working_directory: ~/project
    executor:
      name: golang
    steps:
      - checkout:
          path: ~/project
      - go-install-tools:
          tool: "staticcheck"
      - run: go mod verify
      - run: go mod tidy
      - run:
          name: Check Modules
          command: |
            if [ ! -z "$(git status --porcelain)" ]; then
              git status
              echo
              echo -e '\033[1;93m!!! "go mod verify && go mod tidy" resulted in changes. Please run those commands locally and commit the changes.\e[0m'
              echo
              git diff
              echo
              exit 1
            fi
      - run: go fmt ./...
      - run:
          name: Check gofmt
          command: |
            if [ ! -z "$(git status --porcelain)" ]; then
              git status
              echo
              echo -e '\033[1;93m!!! "go fmt ./..." resulted in changes. Please run it locally and commit the changes.\e[0m'
              echo
              git diff
              echo
              exit 1
            fi
      - run: go generate ./...
      - run:
          name: Check Generated Code
          command: |
            if [ ! -z "$(git status --porcelain)" ]; then
              git status
              echo
              echo -e '\033[1;93m!!! "go generate ./..." resulted in changes. Please codegen locally and commit the changes.\e[0m'
              echo
              git diff
              echo
              exit 1
            fi
      - run: staticcheck ./...
      - run: go vet ./...
      - run: go test ./...
